parameters:
#    blogger_shop.example.class: \ShopBundle\Example
    paypal_email: test@test.com


services:
#    blogger_shop.example:
#        class: %blogger_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
