BloggerShopBundle:
    resource: "@BloggerShopBundle/Resources/config/routing.yml"
    prefix:   /

BloggerGalleryBundle:
    resource: "@BloggerGalleryBundle/Resources/config/routing.yml"
    prefix:   /


        
BloggerBlogBundle_security_login_check:
    pattern:  /login_check
    defaults: { _controller: BloggerBlogBundle:Security:loginCheck }
    requirements:
        _method:  GET|POST
        
BloggerBlogBundle_security_login:
    pattern:  /login
    defaults: { _controller: BloggerBlogBundle:Security:login }
    requirements:
        _method:  GET
        
BloggerBlogBundle_security_logout:
    pattern:  /logout
    defaults: { _controller: BloggerBlogBundle:Security:logout }
    requirements:
        _method:  GET
        
BloggerBlogBundle:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /
    
_imagine:
    resource: .
    type:     imagine