BloggerBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method:  GET
        
BloggerBlogBundle_about:
    pattern:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET
        
BloggerBlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        _method:  GET|POST
        
BloggerBlogBundle_blog_show:
    pattern:  /{id}/{slug}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+
        
BloggerBlogBundle_blog_new:
    pattern:  /new
    defaults: { _controller: BloggerBlogBundle:Blog:new }
    requirements:
        _method:  GET|POST
        id: \d+
        
BloggerBlogBundle_blog_edit:
    pattern:  /{id}/{slug}/edit
    defaults: { _controller: BloggerBlogBundle:Blog:edit }
    requirements:
        _method:  GET|POST
        
BloggerBlogBundle_blog_delete:
    pattern:  /{id}/{slug}/delete
    defaults: { _controller: BloggerBlogBundle:Blog:delete }
    requirements:
        _method:  GET|POST
        
BloggerBlogBundle_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+