parameters:
#    blogger_gallery.example.class: \GalleryBundle\Example

services:
#    blogger_gallery.example:
#        class: %blogger_gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
